[pytest]
addopts = --json-report --json-report-file=test_dashboard/report.json --cov=Prime_Supplements --cov-report=json:test_dashboard/coverage.json --ignore=test_dashboard --ignore=tests/ui --ignore=app.py --ignore=Prime_Supplements --ignore=test_output.txt
